[7390 branch]: * Sync with trunk

diff --git a/branches/oliver/7390/make/rrdstats/files/root/usr/bin/webcfg-rrd b/branches/oliver/7390/make/rrdstats/files/root/usr/bin/webcfg-rrd
--- a/branches/oliver/7390/make/rrdstats/files/root/usr/bin/webcfg-rrd
+++ b/branches/oliver/7390/make/rrdstats/files/root/usr/bin/webcfg-rrd
@@ -1,15 +1,17 @@
 #!/bin/sh
 
+export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/mod/sbin:/mod/bin:/mod/usr/sbin:/mod/usr/bin
+export LD_LIBRARY_PATH=/mod/lib
+
 DAEMON=rrdstats
-. /etc/init.d/modlibrc
-
 SUBDAEMON=rrd
-. /mod/etc/conf/rrdstats.cfg
-homedir=/mod/pkg/rrdstats/usr/mww-$SUBDAEMON/
 
-if [ "$RRDSTATS_WEB_AUTH" = yes ]; then
-	echo "/:$RRDSTATS_WEB_USER:$(httpd -m $RRDSTATS_WEB_PASS)" >/mod/etc/httpd-$SUBDAEMON.conf
-	RRD_CONF="-c /mod/etc/httpd-$SUBDAEMON.conf"
+if [ ! -r "/mod/etc/conf/${DAEMON}.cfg" ]; then
+	echo "Error[$DAEMON]: not configured" 1>&2
+	exit 1
 fi
+. /mod/etc/conf/${DAEMON}.cfg
 
-exec httpd "$@" -p "$RRDSTATS_WEBTCPPORT" $RRD_CONF -h "$homedir" -r "RRDstats"
+homedir=/mod/pkg/rrdstats/usr/mww-${SUBDAEMON}/
+
+exec httpd "$@" -p "$RRDSTATS_WEBTCPPORT" -c /mod/etc/httpd-${SUBDAEMON}.conf -h "$homedir" -r "RRDstats"
diff --git a/branches/oliver/7390/make/vnstat-cgi/files/root/usr/bin/webcfg-vns b/branches/oliver/7390/make/vnstat-cgi/files/root/usr/bin/webcfg-vns
--- a/branches/oliver/7390/make/vnstat-cgi/files/root/usr/bin/webcfg-vns
+++ b/branches/oliver/7390/make/vnstat-cgi/files/root/usr/bin/webcfg-vns
@@ -1,15 +1,17 @@
 #!/bin/sh
 
-DAEMON=vnstat-cgi
-. /etc/init.d/modlibrc
+export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/mod/sbin:/mod/bin:/mod/usr/sbin:/mod/usr/bin
+export LD_LIBRARY_PATH=/mod/lib
 
+DAEMON=vnstat
 SUBDAEMON=vns
-. /mod/etc/conf/vnstat.cfg
-homedir=/mod/pkg/vnstat/usr/mww-$SUBDAEMON/
 
-if [ "$VNSTAT_WEB_AUTH" = yes ]; then
-	echo "/:$VNSTAT_WEB_USER:$(httpd -m $VNSTAT_WEB_PASS)" >/mod/etc/httpd-$SUBDAEMON.conf
-	VNS_CONF="-c /mod/etc/httpd-$SUBDAEMON.conf"
+if [ ! -r "/mod/etc/conf/${DAEMON}.cfg" ]; then
+	echo "Error[$DAEMON]: not configured" 1>&2
+	exit 1
 fi
-		
-exec httpd "$@" -p "$VNSTAT_WEB_PORT" $VNS_CONF -h "$homedir" -r "vnstat"
+. /mod/etc/conf/${DAEMON}.cfg
+
+homedir=/mod/pkg/${DAEMON}/usr/mww-${SUBDAEMON}/
+
+exec httpd "$@" -p "$VNSTAT_WEB_PORT" -c /mod/etc/httpd-${SUBDAEMON}.conf -h "$homedir" -r "vnstat"
