[7390] * Sync with trunk

diff --git a/branches/oliver/7390/root/etc/init.d/modlibrc b/branches/oliver/7390/root/etc/init.d/modlibrc
--- a/branches/oliver/7390/root/etc/init.d/modlibrc
+++ b/branches/oliver/7390/root/etc/init.d/modlibrc
@@ -11,8 +11,10 @@
 # DAEMON_LONG_NAME	${DAEMON}					full name of daemon to display in start/stop messages
 # CONF_NAME			${DAEMON}					config is in /mod/etc/conf/${CONF_NAME}.cfg
 # CONF_ENABLED		${DAEMON}_ENABLED			variablename with starttype of daemon (yes,no,inetd) in .cfg-file
+# DAEMON_CONFIG		/mod/etc/${DAEMON}.conf		modlib_config will generate this file
 # DAEMON_BIN		${DAEMON}					other binary name than $DAEMON
 # DAEMON_ENV		<empty>						additional environment settings
+# DAEMON_CHECK		<empty>						daemon(s) to check with pidof for running-status
 # PID_FILE			/var/run/${DAEMON_BIN}.pid	pid-file for DAEMON
 
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/mod/sbin:/mod/bin:/mod/usr/sbin:/mod/usr/bin
@@ -21,6 +23,7 @@ export LD_LIBRARY_PATH=/mod/lib:/mod/usr/lib
 : ${DAEMON_LONG_NAME:=$DAEMON}
 : ${CONF_NAME:=$DAEMON}
 : ${CONF_ENABLED:=${DAEMON}_ENABLED}
+: ${DAEMON_CONFIG:=/mod/etc/${DAEMON}.conf}
 : ${DAEMON_BIN:=$DAEMON}
 : ${PID_FILE:=/var/run/${DAEMON_BIN}.pid}
 
@@ -46,8 +49,7 @@ reload() {
 #   No check is done for a change in the optional arguments!
 #	$1: group name
 #	$2-n: optional arguments for addgroup
-modlib_addgroup()
-{
+modlib_addgroup() {
 	local group=$1
 	shift
 	if grep -q "^$group:" /etc/group; then
@@ -67,8 +69,7 @@ modlib_addgroup()
 #   No check is done for a change in the optional arguments!
 #	$1: user name
 #	$2-n: optional arguments for adduser
-modlib_adduser()
-{
+modlib_adduser() {
 	local user=$1
 	shift
 	if grep -q "^$user:" /etc/passwd; then
@@ -94,8 +95,7 @@ modlib_adduser()
 #	$3: [optional] command: check(default), stop, kill
 #	$4: [optional] socket: t: TCP(default) u: UDP w: RAW
 #   returns: 0 free; 1 oneself; 2 inetd; 3 other daemon; 4 stop command failed; 5 kill command failed
-modlib_check_port()
-{
+modlib_check_port() {
 	local netport=${1:-21}
 	local daemonname=${2:-daemon}
 	local docommand=${3:-check}
@@ -177,9 +177,17 @@ modlib_check_port()
 #	 3:	stopped
 #	 5:	inetd
 #	use CONF_ENABLED for other variablename with manual/automatic/inetd in .cfg-file
-modlib_check_running()
-{
-	[ "$(eval echo \$$(echo ${CONF_ENABLED} | tr [:lower:]- [:upper:]_))" == "inetd" ] && return 5
+modlib_check_running() {
+	[ -n "$FORCE_STATUS" ] && return $FORCE_STATUS
+	if [ -x /etc/init.d/rc.inetd ]; then
+		[ "$(eval echo \$$(echo ${CONF_ENABLED} | tr [:lower:]- [:upper:]_))" == "inetd" ] && return 5
+	fi
+	if [ -n "$DAEMON_CHECK" ]; then
+		for DAEMON_single in $DAEMON_CHECK; do
+			pidof $DAEMON_single >/dev/null 2>&1 || return 3
+		done
+		return 0
+	fi
 	local fn=$PID_FILE
 	[ ! -s "$fn" ] && return 3
 	if kill -0 $(cat "$fn") 2> /dev/null; then
@@ -190,14 +198,33 @@ modlib_check_running()
 	fi
 }
 
+# modlib_config
+#    creates /mod/etc/$DAEMON.conf
+#    parameters:
+#     $1 (optional): overwrites the $DAEMON part in input filenames
+#	  $2 (optional): overwrites output path+filename, default is $DAEMON_CONFIG (=/mod/etc/${DAEMON}.conf)
+modlib_config() {
+	local in_files=${1-$DAEMON}
+	local out_file=${2-$DAEMON_CONFIG}
+	(
+		if [ -x "/tmp/flash/${in_files}_conf" ]; then
+			/tmp/flash/${in_files}_conf
+		elif [ -x "/tmp/flash/${DAEMON}/${in_files}_conf" ]; then
+			/tmp/flash/${DAEMON}/${in_files}_conf
+		else
+			/mod/etc/default.${DAEMON}/${in_files}_conf
+		fi
+		cat /tmp/flash/${in_files}.extra /tmp/flash/${DAEMON}/${in_files}.extra 2>/dev/null
+	) > $out_file
+}
+
 # modlib_startdaemon
 #    starts the binary with a clean environment
 #    "$@": commandline to execute
 #    if available runs "config" of rc.$DAEMON
 #    use $DAEMON_BIN for other binary name than $DAEMON
 #    use $DAEMON_ENV for additional environment settings
-modlib_startdaemon()
-{
+modlib_startdaemon() {
 	echo -n "Starting ${DAEMON_LONG_NAME} ... "
 	config
 
@@ -228,17 +255,14 @@ modlib_startdaemon()
 #    function "start" has to be defined in the calling script
 #    $1: value for DAEMON_ENABLED
 #    returns: 0=success or 1=error
-modlib_start()
-{
+modlib_start() {
 	local DAEMON_ENABLED=$1
-	if [ "$DAEMON_ENABLED" == "no" -o "$DAEMON_ENABLED" == "inetd" -a -x /etc/init.d/rc.inetd ]; then
-		if [ "$DAEMON_ENABLED" != "inetd" ]; then
-			echo "${DAEMON_LONG_NAME} is disabled." 1>&2
-		else
-			echo "${DAEMON_LONG_NAME} is started via inetd." 1>&2
-			config
-		fi
+	if [ "$DAEMON_ENABLED" == "no" ]; then
+		echo "${DAEMON_LONG_NAME} is disabled." 1>&2
 		exit 1
+	fi
+	if [ "$DAEMON_ENABLED" == "inetd" -a ! -x /etc/init.d/rc.inetd ]; then
+		echo "WARNING: ${DAEMON_LONG_NAME} could not find inetd." 1>&2
 	fi
 
 	modlib_check_running
@@ -251,7 +275,8 @@ modlib_start()
 			return $?
 			;;
 		5)
-			echo "${DAEMON_LONG_NAME} is started via inetd." 1>&2
+			config
+			/etc/init.d/rc.inetd config $DAEMON
 			;;
 		*)
 			echo "${DAEMON_LONG_NAME} start prohibited, status is uncertain!" 1>&2
@@ -260,11 +285,20 @@ modlib_start()
 	return 1
 }
 
+# modlib_force_start
+#   forces start of the daemon
+modlib_force_start() {
+	if [ -x /etc/init.d/rc.inetd ]; then
+		config
+		/etc/init.d/rc.inetd config $DAEMON
+	fi
+	modlib_start
+}
+
 # modlib_stop
 #   stops the daemon
 #	kills daemon with "stop" of rc.$DAEMON if available
-modlib_stop()
-{
+modlib_stop() {
 	local fn=$PID_FILE
 	local id=$(cat "$fn" 2>/dev/null)
 	echo -n "Stopping ${DAEMON_LONG_NAME} ... "
@@ -272,26 +306,30 @@ modlib_stop()
 	case $? in
 		0)
 			stop
-			if [ $? -ne 127 ]; then
+			local retval=$?
+			if [ "$retval" -ne 127 ]; then
 				sleep 1
 			else
+				local retval=0
 				local cnt=9
 				while [ $cnt -ge 0 ] && kill -0 $id 2>/dev/null; do
 					kill $id 2>/dev/null
+					local retval=$?
 					sleep 1
 					let cnt--
 				done
 				if kill -0 $id 2>/dev/null; then
 					kill -9 $id 2>/dev/null
+					local retval=$?
 					sleep 1
 				fi
 			fi
-			if ! kill -0 $id 2>/dev/null; then
+			if ! kill -0 $id 2>/dev/null && [ "$retval" -eq 0 ]; then
 				rm -f "$fn"
 				echo 'done.'
 			else
 				echo 'failed.'
-				return 1
+				return $retval
 			fi
 			;;
 		3)
@@ -308,20 +346,39 @@ modlib_stop()
 	esac
 }
 
+# modlib_force_stop
+#   forces stop of the daemon
+modlib_force_stop() {
+	echo -n "Stopping ${DAEMON_LONG_NAME} forced ... "
+	FORCE_STATUS="0"
+	modlib_stop >/dev/null
+	if [ -e /etc/default.$DAEMON/*.inetd ]; then
+		FORCE_STATUS="5"
+		modlib_stop >/dev/null
+	fi
+	FORCE_STATUS=""
+	echo 'done.'
+}
+
 # modlib_restart
 #   restarts the daemon
-modlib_restart()
-{
+modlib_restart() {
 	modlib_stop
 	modlib_start
+}
+
+# modlib_force_restart
+#   forces restart of the daemon
+modlib_force_restart() {
+	modlib_force_stop
+	modlib_force_start
 }
 
 # modlib_reload
 #   reloads the daemon with SIGHUP
 #   if available runs "config" of rc.$DAEMON
 #	reloads daemon with "reload" of rc.$DAEMON if available
-modlib_reload()
-{
+modlib_reload() {
 	local fn=$PID_FILE
 	echo -n "Reloading ${DAEMON_LONG_NAME} ... "
 	modlib_check_running
@@ -330,21 +387,21 @@ modlib_reload()
 			config
 
 			reload 0
-			local status=$?
-			if [ $status -ne 127 ]; then
+			local retval=$?
+			if [ $retval -ne 127 ]; then
 				sleep 1
 			else
 				kill -HUP $(cat "$fn") 2> /dev/null
-				local status=$?
+				local retval=$?
 			fi
 
-			if [ $status -eq 0 ]; then
+			if [ $retval -eq 0 ]; then
 				echo 'done.'
 				return 0
 			else
 				rm -f "$fn"
 				echo 'failed.'
-				return 1
+				return $retval
 			fi
 			;;
 		3)
@@ -372,8 +429,7 @@ modlib_reload()
 #	3:			stopped
 #	5:			inetd
 #	<other>:	unknown
-modlib_status()
-{
+modlib_status() {
 	modlib_check_running
 	retval=$?
 	case $retval in
@@ -395,8 +451,7 @@ modlib_status()
 
 # modlib_loadconfig
 #    loads the configuration
-modlib_loadconfig()
-{
+modlib_loadconfig() {
 	local CONF_FILE="/mod/etc/conf/${1-$CONF_NAME}.cfg"
 	if [ ! -r "$CONF_FILE" ]; then
 		echo "Error[${DAEMON_LONG_NAME}]: not configured" 1>&2
