![7390]: Sync with trunk

diff --git a/branches/oliver/7390/make/mod/files/root/etc/init.d/modlibrc b/branches/oliver/7390/make/mod/files/root/etc/init.d/modlibrc
--- a/branches/oliver/7390/make/mod/files/root/etc/init.d/modlibrc
+++ b/branches/oliver/7390/make/mod/files/root/etc/init.d/modlibrc
@@ -58,7 +58,7 @@ modlib_addgroup() {
 	echo -n "Looking for group '$group' ... "
 	if addgroup "$@" "$group"; then
 		echo -n "created - now saving to data buffer ... "
-		modusers save && echo "done" || echo "failed"
+		modusers save && echo "done." || echo "failed."
 	else
 		echo "not created - error occurred"
 	fi
@@ -79,7 +79,7 @@ modlib_adduser() {
 	local msg=$(adduser "$@" "$user" 2>&1)
 	if [ $? -eq 0 ]; then
 		echo -n "created - now saving to data buffer ... "
-		modusers save && echo "done" || echo "failed"
+		modusers save && echo "done." || echo "failed."
 	else
 		echo "not created - error occurred: $msg"
 		exit 1
@@ -144,7 +144,7 @@ modlib_startdaemon() {
 	echo -n "Starting ${DAEMON_LONG_NAME} ... "
 	config
 
-	env - PATH="$PATH" $DAEMON_ENV "$@"
+	env - PATH="$PATH" $DAEMON_ENV "$@" 1>&2
 	local rv=$?
 
 	if [ $rv -ne 0 ]; then
