Merging [4684:4723/trunk]

diff --git a/branches/buehmann/url-space/root/usr/bin/freetz_status b/branches/buehmann/url-space/root/usr/bin/freetz_status
--- a/branches/buehmann/url-space/root/usr/bin/freetz_status
+++ b/branches/buehmann/url-space/root/usr/bin/freetz_status
@@ -1,6 +1,14 @@
 #!/bin/sh
 
 . /usr/lib/libmodredir.sh
+
+if [ ! -r "/mod/etc/conf/mod.cfg" -o ! -r "/mod/etc/init.d/rc.webcfg" ]; then
+    	CRLF=$'\r\n'
+	echo -n "Content-Type: text/plain${CRLF}${CRLF}"
+	echo "Error[webcfg]: not configured"
+	exit 1
+fi
+
 . /mod/etc/conf/mod.cfg
 
 log=
@@ -10,6 +18,6 @@ show_log() {
   
 status=$(/mod/etc/init.d/rc.webcfg status)
 [ "$status" = "running" -o "$status" = "inetd" ] || \
-	log="$(/mod/etc/init.d/rc.webcfg start 2>&1)"
+	log=$(/mod/etc/init.d/rc.webcfg start 2>&1)
 
 redirect "http://$(self_host):$MOD_HTTPD_PORT/" "Freetz" show_log
